"""empty message

Revision ID: 41b0247a0f3b
Revises: fe64c4a54669
Create Date: 2023-08-01 14:38:31.210658

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41b0247a0f3b'
down_revision = 'fe64c4a54669'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bookings2')
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'treatments', ['treatment_id'], ['id'])
        batch_op.drop_column('treatment_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('treatment_name', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')

    op.create_table('bookings2',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('customer_name', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('booking_date', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('booking_time', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('treatment_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('treatment_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['treatment_id'], ['treatments.id'], name='bookings_treatment_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='bookings_pkey')
    )
    # ### end Alembic commands ###
